name: learn-github-actions
run-name: ${{ github.actor }} GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - run: rsync -avzh --exclude='.git' -e 'ssh -i ~/.shh/id_rsa' --rsync-path='sudo rsync' ~/home-page/* ubuntu@18.191.82.204:/var/www/landing